#官方仓库地址
source 'https://github.com/CocoaPods/Specs.git'

#私有仓库地址
source ‘http://code.iotplat.net/privatepods/oncountdownbutton.git’
source ‘http://code.iotplat.net/privatepods/onplaceholder.git’
source ‘http://code.iotplat.net/privatepods/onfoundation.git’

platform :ios, '8.0'
use_frameworks!

target 'Arita' do
    pod 'SnapKit', '3.2.0'
    pod 'MJRefresh', '3.1.12'
    pod 'MBProgressHUD', '1.0.0'
    pod 'WebViewJavascriptBridge', '6.0.2'
    pod 'Toaster', '2.0.3'
    pod 'XCGLogger', '5.0.1'
    pod 'SwiftyJSON', '3.1.4'
    pod 'Kingfisher', '3.7.2'
    pod 'Alamofire', '4.4.0'
    pod 'ALCameraViewController', '1.3.1'
    pod 'HandyJSON', '1.6.1'
    pod 'Bugly', '2.4.8'
    pod 'IQKeyboardManagerSwift', '4.0.10'

    pod 'ONPlaceholder', '0.9.5'
    pod 'ONCountDownButton', '0.2.0'
    pod 'ONFoundation', '0.2.1'
end
